export const CREATE_TEAM_REQUEST = 'CREATE_TEAM_REQUEST';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_FAIL = 'CREATE_TEAM_FAIL';

export const ALL_TEAMS_REQUEST = 'ALL_TEAMS_REQUEST';
export const ALL_TEAMS_SUCCESS = 'ALL_TEAMS_SUCCESS';
export const ALL_TEAMS_FAIL = 'ALL_TEAMS_FAIL';

export const GET_TEAM_BY_ID_REQUEST = 'GET_TEAM_BY_ID_REQUEST';
export const GET_TEAM_BY_ID_SUCCESS = 'GET_TEAM_BY_ID_SUCCESS';
export const GET_TEAM_BY_ID_FAIL = 'GET_TEAM_BY_ID_FAIL';

export const UPDATE_TEAM_BY_ID_REQUEST = 'UPDATE_TEAM_BY_ID_REQUEST';
export const UPDATE_TEAM_BY_ID_SUCCESS = 'UPDATE_TEAM_BY_ID_SUCCESS';
export const UPDATE_TEAM_BY_ID_FAIL = 'UPDATE_TEAM_BY_ID_FAIL';

export const DELETE_TEAM_BY_ID_REQUEST = 'DELETE_TEAM_BY_ID_REQUEST';
export const DELETE_TEAM_BY_ID_SUCCESS = 'DELETE_TEAM_BY_ID_SUCCESS';
export const DELETE_TEAM_BY_ID_FAIL = 'DELETE_TEAM_BY_ID_FAIL';

export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL';

export const GET_ALL_TASKS_REQUEST = 'GET_ALL_TASKS_REQUEST';
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS';
export const GET_ALL_TASKS_FAIL = 'GET_ALL_TASKS_FAIL';

export const UPDATE_TASK_BY_ID_REQUEST = 'UPDATE_TASK_BY_ID_REQUEST';
export const UPDATE_TASK_BY_ID_SUCCESS = 'UPDATE_TASK_BY_ID_SUCCESS';
export const UPDATE_TASK_BY_ID_FAIL = 'UPDATE_TASK_BY_ID_FAIL';

export const DELETE_TASK_BY_ID_REQUEST = 'DELETE_TASK_BY_ID_REQUEST';
export const DELETE_TASK_BY_ID_SUCCESS = 'DELETE_TASK_BY_ID_SUCCESS';
export const DELETE_TASK_BY_ID_FAIL = 'DELETE_TASK_BY_ID_FAIL';

export const GET_ALL_TASKS_FOR_TEAM_MEMBERS_REQUEST = 'GET_ALL_TASKS_FOR_TEAM_MEMBERS_REQUEST';
export const GET_ALL_TASKS_FOR_TEAM_MEMBERS_SUCCESS = 'GET_ALL_TASKS_FOR_TEAM_MEMBERS_SUCCESS';
export const GET_ALL_TASKS_FOR_TEAM_MEMBERS_FAIL = 'GET_ALL_TASKS_FOR_TEAM_MEMBERS_FAIL';

export const GET_TASK_BY_ID_FOR_USER_REQUEST = 'GET_TASK_BY_ID_FOR_USER_REQUEST';
export const GET_TASK_BY_ID_FOR_USER_SUCCESS = 'GET_TASK_BY_ID_FOR_USER_SUCCESS';
export const GET_TASK_BY_ID_FOR_USER_FAIL = 'GET_TASK_BY_ID_FOR_USER_FAIL';

export const UPDATE_COMPLETION_STATUS_REQUEST = 'UPDATE_COMPLETION_STATUS_REQUEST';
export const UPDATE_COMPLETION_STATUS_SUCCESS = 'UPDATE_COMPLETION_STATUS_SUCCESS';
export const UPDATE_COMPLETION_STATUS_FAIL = 'UPDATE_COMPLETION_STATUS_FAIL';

export const GET_ALL_NOTIFICATIONS_REQUEST = 'GET_ALL_NOTIFICATIONS_REQUEST';
export const GET_ALL_NOTIFICATIONS_SUCCESS = 'GET_ALL_NOTIFICATIONS_SUCCESS';
export const GET_ALL_NOTIFICATIONS_FAIL = 'GET_ALL_NOTIFICATIONS_FAIL';

export const UPDATE_NOTIFICATION_READ_STATUS_REQUEST = 'UPDATE_NOTIFICATION_READ_STATUS_REQUEST';
export const UPDATE_NOTIFICATION_READ_STATUS_SUCCESS = 'UPDATE_NOTIFICATION_READ_STATUS_SUCCESS';
export const UPDATE_NOTIFICATION_READ_STATUS_FAIL = 'UPDATE_NOTIFICATION_READ_STATUS_FAIL';

export const GET_ALL_TASK_COMPLETIONS_REQUEST = 'GET_ALL_TASK_COMPLETIONS_REQUEST';
export const GET_ALL_TASK_COMPLETIONS_SUCCESS = 'GET_ALL_TASK_COMPLETIONS_SUCCESS';
export const GET_ALL_TASK_COMPLETIONS_FAIL = 'GET_ALL_TASK_COMPLETIONS_FAIL';

export const GET_TASK_COMPLETION_BY_ID_REQUEST = 'GET_TASK_COMPLETION_BY_ID_REQUEST';
export const GET_TASK_COMPLETION_BY_ID_SUCCESS = 'GET_TASK_COMPLETION_BY_ID_SUCCESS';
export const GET_TASK_COMPLETION_BY_ID_FAIL = 'GET_TASK_COMPLETION_BY_ID_FAIL';

export const GET_TEAMS_BY_USER_ID_REQUEST = 'GET_TEAMS_BY_USER_ID_REQUEST';
export const GET_TEAMS_BY_USER_ID_SUCCESS = 'GET_TEAMS_BY_USER_ID_SUCCESS';
export const GET_TEAMS_BY_USER_ID_FAIL = 'GET_TEAMS_BY_USER_ID_FAIL';

export const RESET_STATE = 'RESET_STATE';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
